classifier_path: baseline_logreg_l12.joblib
model_path: models/cross-encoder-ms-marco-MiniLM-L12-v2
fasttext_path: models/fasttext_model.model
items_path: data/items_human_normalized.parquet
matches_path: data/matches.parquet
output_path: predictions.csv
device: null
batch_size: 512
backend: pytorch

hydra:
  job:
    chdir: false
  run:
    dir: .
  output_subdir: null
